# Extract

In [1]:
import pandas as pd

In [2]:
# Load the CSV file
file_path = r"C:\Users\Huawei\Downloads\New folder\Case_Information.csv"
df = pd.read_csv(file_path)

# Display the first few rows of the dataframe
df.head()

,case_id,age,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
0,C404174,38.0,35 to 39,Female,2020-01-30,NaN,NaN,Recovered,2020-02-07,Negros Oriental,Dumaguete City,Recovered,NaN,2020-01-21,NaN,Central Visayas (Region VII)
1,C462688,44.0,40 to 44,Male,2020-02-03,NaN,2020-02-01,Died,2020-02-02,Negros Oriental,Dumaguete City,Died,NaN,2020-01-18,NaN,Central Visayas (Region VII)
2,C387710,60.0,60 to 64,Female,2020-02-05,2020-01-31,NaN,Recovered,2020-02-05,Bohol,Panglao,Recovered,No,2020-01-21,NaN,Central Visayas (Region VII)
3,C377460,48.0,45 to 49,Male,2020-03-06,NaN,NaN,Recovered,2020-03-27,Metropolitan Manila,Taguig,Recovered,No,2020-03-03,NaN,Metropolitan Manila
4,C498051,62.0,60 to 64,Male,2020-03-06,NaN,2020-03-11,Died,2020-03-12,Rizal,Cainta,Died,No,2020-02-25,NaN,CALABARZON (Region IV-A)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12091 entries, 0 to 12090
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   case_id                    12091 non-null  object
 1   age                        12070 non-null  float64
 2   age_group                  12070 non-null  object
 3   sex                        12091 non-null  object
 4   date_announced             12091 non-null  object
 5   date_recovered             1237 non-null   object
 6   date_of_death              657 non-null    object
 7   status                     12091 non-null  object
 8   date_announced_as_removed  3266 non-null   object
 9   province                   11053 non-null  object
 10  muni_city                  11053 non-null  object
 11  health_status              12091 non-null  object
 12  home_quarantined           5310 non-null   object
 13  date_of_onset_of_symptoms  6561 non-null   object
 14  pregnant                   1925 non-null   object
 15  region                     11053 non-null  object
dtypes: float64(1), object(15)
memory usage: 1.5+ MB

In [5]:

# Fill missing 'age' with the mean of the column
df['age'].fillna(df['age'].mean(), inplace=True)

# Fill missing 'age_group' based on the 'age' column (assuming 'age_group' is a categorical representation of 'age')
df['age_group'] = df['age_group'].fillna(df['age'].apply(lambda x: '0-9' if x < 10 else '10-19' if x < 20 else '20-29' if x < 30 else '30-39' if x < 40 else '40-49' if x < 50 else '50-59' if x < 60 else '60-69' if x < 70 else '70-79' if x < 80 else '80+'))

# Fill missing 'province', 'muni_city', and 'region' with 'Unknown'
df['province'].fillna('Unknown', inplace=True)
df['muni_city'].fillna('Unknown', inplace=True)
df['region'].fillna('Unknown', inplace=True)

# Fill missing 'date_recovered', 'date_of_death', 'date_announced_as_removed', and 'date_of_onset_of_symptoms' with a placeholder date
df['date_recovered'].fillna('1900-01-01', inplace=True)
df['date_of_death'].fillna('1900-01-01', inplace=True)
df['date_announced_as_removed'].fillna('1900-01-01', inplace=True)
df['date_of_onset_of_symptoms'].fillna('1900-01-01', inplace=True)

# For 'home_quarantined' and 'pregnant', we can assume 'No' for missing values if this makes sense in your context
df['home_quarantined'].fillna('No', inplace=True)
df['pregnant'].fillna('No', inplace=True)

# Now, check if there are still missing values
missing_data = df.isnull().sum()
print(missing_data)

# You can also forward fill or backward fill where it makes sense
df.fillna(method='ffill', inplace=True)

# Print the cleaned DataFrame
df.head()

case_id                      0
age                          0
age_group                    0
sex                          0
date_announced               0
date_recovered               0
date_of_death                0
status                       0
date_announced_as_removed    0
province                     0
muni_city                    0
health_status                0
home_quarantined             0
date_of_onset_of_symptoms    0
pregnant                     0
region                       0
dtype: int64

C:\Users\Huawei\AppData\Local\Temp\ipykernel_14840\2754122205.py:27: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

,case_id,age,age_group,sex,date_announced,date_recovered,date_of_death,status,date_announced_as_removed,province,muni_city,health_status,home_quarantined,date_of_onset_of_symptoms,pregnant,region
0,C404174,38.0,35 to 39,Female,2020-01-30,1900-01-01,1900-01-01,Recovered,2020-02-07,Negros Oriental,Dumaguete City,Recovered,No,2020-01-21,No,Central Visayas (Region VII)
1,C462688,44.0,40 to 44,Male,2020-02-03,1900-01-01,2020-02-01,Died,2020-02-02,Negros Oriental,Dumaguete City,Died,No,2020-01-18,No,Central Visayas (Region VII)
2,C387710,60.0,60 to 64,Female,2020-02-05,2020-01-31,1900-01-01,Recovered,2020-02-05,Bohol,Panglao,Recovered,No,2020-01-21,No,Central Visayas (Region VII)
3,C377460,48.0,45 to 49,Male,2020-03-06,1900-01-01,1900-01-01,Recovered,2020-03-27,Metropolitan Manila,Taguig,Recovered,No,2020-03-03,No,Metropolitan Manila
4,C498051,62.0,60 to 64,Male,2020-03-06,1900-01-01,2020-03-11,Died,2020-03-12,Rizal,Cainta,Died,No,2020-02-25,No,CALABARZON (Region IV-A)